const constants = {
	SEARCH_QUERY: "SEARCH_QUERY",
	ITEMS: "ITEMS",
	DELETE_ITEM: "DELETE_ITEM",
	MOVE_ITEM_TO_TOP: "MOVE_ITEM_TO_TOP",
	SELECTED_ITEM:"SELECTED_ITEM",
	DELETE_BULK: "DELETE_BULK",
	MOVE_BULK: "MOVE_BULK",
	CLEAR_SELECTED_ITEMS: "CLEAR_SELECTED_ITEMS",
	TOTAL_SELECTED_ITEMS: "TOTAL_SELECTED_ITEMS"
}

export default constants